### ISSUE TITLE
Lets Finish this sitão da poha

### ISSUE THREAD

**Issue by marcelobbfonseca** [pedrotst/pedrotst.github.io#1]
Completa seu lindo site pra facilitar os stalks. Usei esse template https://deanattali.com/beautiful-jekyll/ pra criar o meu. Ficou topzinho

**Comment by pedrotst** [comment]
oxe, esse aqui ficou perdido pq não gostei do link e nunca apaguei haha
Meu site mesmo é esse aqui
https://pedroabreu0.github.io/
